spring:
  application:
    name: provider

eureka:
  instance:
    #默认 主机名：服务名称：服务端口
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
server:
  port: 8001