spring:
  application:
    name: consumer-order81

server:
  port: 81

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/


ribbon:
#  eureka:
#    enabled: false
  ConnectTimeout: 500 #连接超时时间
  ReadTimeout: 200 #业务逻辑处理超时时间
  MaxAutoRetriesNextServer: 3 #同一个服务其他实例的最大重试次数，不包括首次调用的实例(POST请求要是重试会有风险的)
  MaxAutoRetries: 0 #同一实例最大重试次数，不包括首次调用(POST请求要是重试会有风险的)
  OkToRetryOnAllOperations: false #是否对所有操作都重试，如果改为 true，则对所有操作请求都进行重试
  restclient:
    enabled: true


feign:
  hystrix:
    enabled: true

#provider:
#  ribbon:
#    listOfServers: localhost:8001,localhost:8002