server:
  port: 80

spring:
  security:
    user:
      name: yejiang
      password: 123
  thymeleaf:
    mode: HTML
    suffix: .html
    prefix: classpath:/static/
    cache: false
    enabled: true
    encoding: UTF-8
  ## jpa配置
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.hbm2ddl: update
      show-sql: true
  ## 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.51sou.top:3306/cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

