server:
  port: 80

spring:
  security:
    user:
      name: yejiang
      password: 123
  thymeleaf:
    mode: HTML
    suffix: .html
    prefix: classpath:/static/
    cache: false
    enabled: true
    encoding: UTF-8

